name: manual-avatar-generator
on:
  workflow_dispatch:  # 手動実行のみ

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install openai==1.* pillow requests

      - name: Generate avatars & update JSON
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/gen_avatar_batch.py

      - name: Commit & push if changed
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add avatars scholars.json
          git diff --staged --quiet || (git commit -m "Auto-update avatars" && git push)
